package view;

import controller.GestionePersonale.AssumiLicenziaControl;
import controller.AreaPersonale.CambiaPasswordControl;
import controller.AreaPersonale.FirmaControl;
import controller.AreaPersonale.OrariStipendiControl;
import controller.AreaPersonale.RichiesteControl;
import controller.Autenticazione.LoginControl;
import controller.Autenticazione.RecuperaPasswordControl;
import misc.RistabilisciConnessioneControl;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Utente
 */
public class Errore extends javax.swing.JFrame {

    /**
     * Creates new form Errore
     */
    private CambiaPasswordControl CPC;
    private FirmaControl FC;
    private OrariStipendiControl OSC;
    private RichiesteControl RC;
    private LoginControl LC;
    private RecuperaPasswordControl RPC;
    private RistabilisciConnessioneControl RCC;
    private AssumiLicenziaControl ALC;

    public Errore(String messaggio, Object controller) {
        if (controller instanceof CambiaPasswordControl) {
            this.CPC = (CambiaPasswordControl) controller;
        }
        if (controller instanceof FirmaControl) {
            this.FC = (FirmaControl) controller;
        }
        if (controller instanceof OrariStipendiControl) {
            this.OSC = (OrariStipendiControl) controller;
        }
        if (controller instanceof RichiesteControl) {
            this.RC = (RichiesteControl) controller;
        }
        if (controller instanceof LoginControl) {
            this.LC = (LoginControl) controller;
        }
        if (controller instanceof RecuperaPasswordControl) {
            this.RPC = (RecuperaPasswordControl) controller;
        }
        if (controller instanceof RistabilisciConnessioneControl) {
            this.RCC = (RistabilisciConnessioneControl) controller;
        }
        if (controller instanceof AssumiLicenziaControl) {
            this.ALC = (AssumiLicenziaControl) controller;
        }
        initComponents();
        jTextField1.setText(messaggio);
        this.setVisible(true);
        this.setAlwaysOnTop(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConfirmButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ConfirmButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        ConfirmButton1.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        ConfirmButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ConfirmButton.png"))); // NOI18N
        ConfirmButton1.setText("Conferma");
        ConfirmButton1.setAlignmentY(0.0F);
        ConfirmButton1.setBorder(null);
        ConfirmButton1.setBorderPainted(false);
        ConfirmButton1.setContentAreaFilled(false);
        ConfirmButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ConfirmButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ConfirmButton1.setIconTextGap(0);
        ConfirmButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        ConfirmButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 248, 238));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ERRORE!");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(225, 24, 139, 48);

        ConfirmButton2.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        ConfirmButton2.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ConfirmButton.png"))); // NOI18N
        ConfirmButton2.setText("Conferma");
        ConfirmButton2.setAlignmentY(0.0F);
        ConfirmButton2.setBorder(null);
        ConfirmButton2.setBorderPainted(false);
        ConfirmButton2.setContentAreaFilled(false);
        ConfirmButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ConfirmButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ConfirmButton2.setIconTextGap(0);
        ConfirmButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        ConfirmButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(ConfirmButton2);
        ConfirmButton2.setBounds(202, 320, 195, 50);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 248, 238));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("testo notifica");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(50, 100, 500, 190);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBounds(660, 50, 600, 400);
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmButton1ActionPerformed

    private void ConfirmButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmButton2ActionPerformed
        // TODO add your handling code here:
        if (this.CPC != null) {
            CPC.SubmitError(this);
        }
        if (this.FC != null) {
            FC.SubmitError(this);
        }
        if (this.LC != null) {
            LC.SubmitError(this);
        }
        if (this.RPC != null) {
            RPC.SubmitError(this);
        }
        if (this.RCC != null) {
            RCC.SubmitError(this);
        }
        if (this.ALC != null) {
            ALC.SubmitError(this);
        }
        if (this.OSC != null) {
            OSC.SubmitError(this);
        }
        if (this.RC != null) {
            RC.SubmitError(this);
        }
    }//GEN-LAST:event_ConfirmButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Errore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Errore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Errore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Errore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Errore().setVisible(true);
            } 
        }); */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmButton1;
    private javax.swing.JButton ConfirmButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private boolean clickable;

    public boolean isClickable() {
        return clickable;
    }

    public void setClickable(boolean clickable) {
        this.clickable = clickable;
    }
}
