/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package view;

import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import controller.LoginControl;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.util.HashMap;
import java.util.Map;
/**
 *
 * @author Davide
 */
public class LoginForm extends javax.swing.JFrame {
    LoginControl lc;
    
    public LoginForm(LoginControl lc) {
        initComponents();
        this.setSize(1920,1080);
        this.lc = lc;
        this.getContentPane().setBackground(this.getBackground());
        Map<TextAttribute, Integer> fontAttributes = new HashMap<TextAttribute, Integer>();
        fontAttributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        Font underline = new Font("Segoe UI",Font.PLAIN, 18).deriveFont(fontAttributes);
        this.forgotButton.setFont(underline);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        emailField = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane6 = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPane7 = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextPane8 = new javax.swing.JTextPane();
        matricolaField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        confermaButton = new javax.swing.JButton();
        forgotButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 248, 238));
        setBounds(new java.awt.Rectangle(0, 0, 1920, 1080));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.orange);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(255, 248, 238));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(new java.awt.Color(255, 248, 238));
        jPanel3.setPreferredSize(new java.awt.Dimension(911, 245));

        emailField.setBackground(new java.awt.Color(219, 213, 205));
        emailField.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        emailField.setToolTipText("");
        emailField.setBorder(null);

        jScrollPane6.setBackground(new java.awt.Color(60, 63, 65));
        jScrollPane6.setBorder(null);

        jTextPane6.setEditable(false);
        jTextPane6.setBackground(new java.awt.Color(255, 248, 238));
        jTextPane6.setBorder(null);
        jTextPane6.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jTextPane6.setForeground(new java.awt.Color(0, 0, 0));
        jTextPane6.setText("E-Mail:");
        jTextPane6.setDoubleBuffered(true);
        jTextPane6.setFocusable(false);
        jScrollPane6.setViewportView(jTextPane6);

        jScrollPane7.setBackground(new java.awt.Color(60, 63, 65));
        jScrollPane7.setBorder(null);

        jTextPane7.setEditable(false);
        jTextPane7.setBackground(new java.awt.Color(255, 248, 238));
        jTextPane7.setBorder(null);
        jTextPane7.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jTextPane7.setForeground(new java.awt.Color(0, 0, 0));
        jTextPane7.setText("Password:");
        jTextPane7.setFocusable(false);
        jScrollPane7.setViewportView(jTextPane7);

        jScrollPane8.setBackground(new java.awt.Color(60, 63, 65));
        jScrollPane8.setBorder(null);

        jTextPane8.setEditable(false);
        jTextPane8.setBackground(new java.awt.Color(255, 248, 238));
        jTextPane8.setBorder(null);
        jTextPane8.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jTextPane8.setForeground(new java.awt.Color(0, 0, 0));
        jTextPane8.setText("Matricola:");
        jTextPane8.setFocusable(false);
        jScrollPane8.setViewportView(jTextPane8);

        matricolaField.setBackground(new java.awt.Color(219, 213, 205));
        matricolaField.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        matricolaField.setBorder(null);

        passwordField.setBackground(new java.awt.Color(219, 213, 205));
        passwordField.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        passwordField.setBorder(null);
        passwordField.setPreferredSize(new java.awt.Dimension(116, 32));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(matricolaField)
                    .addComponent(emailField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6)
                    .addComponent(emailField))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7)
                    .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane8)
                    .addComponent(matricolaField))
                .addGap(8, 8, 8))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 611;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(180, 289, 0, 288);
        jPanel1.add(jPanel3, gridBagConstraints);

        confermaButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        confermaButton.setForeground(new java.awt.Color(255, 255, 255));
        confermaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ConfirmButton.png"))); // NOI18N
        confermaButton.setText("Conferma");
        confermaButton.setBorder(null);
        confermaButton.setBorderPainted(false);
        confermaButton.setContentAreaFilled(false);
        confermaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confermaButton.setFocusable(false);
        confermaButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        confermaButton.setMaximumSize(new java.awt.Dimension(3, 161));
        confermaButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/ConfirmButton-selected.png"))); // NOI18N
        confermaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confermaButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 643, 0, 0);
        jPanel1.add(confermaButton, gridBagConstraints);

        forgotButton.setBackground(new java.awt.Color(255, 248, 238));
        forgotButton.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        forgotButton.setForeground(new java.awt.Color(0, 0, 0));
        forgotButton.setText("Hai dimenticato la password?");
        forgotButton.setBorder(null);
        forgotButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgotButton.setFocusPainted(false);
        forgotButton.setFocusable(false);
        forgotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 628, 133, 0);
        jPanel1.add(forgotButton, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(255, 248, 238));

        jScrollPane5.setBackground(new java.awt.Color(255, 248, 238));
        jScrollPane5.setBorder(null);

        jTextPane5.setEditable(false);
        jTextPane5.setBackground(new java.awt.Color(255, 248, 238));
        jTextPane5.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jTextPane5.setForeground(new java.awt.Color(0, 0, 0));
        jTextPane5.setText("Benvenuto!");
        jTextPane5.setFocusable(false);
        jScrollPane5.setViewportView(jTextPane5);

        jButton1.setBackground(new java.awt.Color(255, 248, 238));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/closeIcon.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 339, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 333;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 289, 0, 0);
        jPanel1.add(jPanel2, gridBagConstraints);

        getContentPane().add(jPanel1);

        setBounds(0, 0, 1488, 993);
    }// </editor-fold>//GEN-END:initComponents

    private void confermaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confermaButtonActionPerformed
        lc.dataSubmit();
    }//GEN-LAST:event_confermaButtonActionPerformed

    private void forgotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotButtonActionPerformed
        lc.RPButtonPressed();
    }//GEN-LAST:event_forgotButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
            //</editor-fold>
        

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });*/
        new LoginControl().createLogin();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confermaButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JButton forgotButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextPane jTextPane5;
    private javax.swing.JTextPane jTextPane6;
    private javax.swing.JTextPane jTextPane7;
    private javax.swing.JTextPane jTextPane8;
    private javax.swing.JTextField matricolaField;
    private javax.swing.JPasswordField passwordField;
    // End of variables declaration//GEN-END:variables

    public JButton getConfermaButton() {
        return confermaButton;
    }

    public JTextField getEmailField() {
        return emailField;
    }

    public JButton getForgotButton() {
        return forgotButton;
    }

    public JTextField getMatricolaField() {
        return matricolaField;
    }

    public JPasswordField getPasswordField() {
        return passwordField;
    }
    
    private boolean clickable;

    public boolean isClickable() {
        return clickable;
    }

    public void setClickable(boolean clickable) {
        this.clickable = clickable;
    }
    
}
