package view;

import controller.AreaPersonale.OrariStipendiControl;
import javax.swing.JLabel;
import javax.swing.JTable;

public class OrarioImpiegato extends javax.swing.JFrame {

    /**
     * Creates new form OrarioImpiegatoDatore
     */
    public OrarioImpiegato(OrariStipendiControl OSC) {
        this.OSC = OSC;
        initComponents();
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        this.setVisible(true);
        this.setAlwaysOnTop(true);
        

    }

    public OrarioImpiegato(OrariStipendiControl OSC, String nome, String cognome, String matricola) {
        this.OSC = OSC;
        initComponents();
        jLabel1.setText("Impiegato Selezionato: " + nome + " " + cognome);
        jLabel2.setText("Matricola: " + matricola);
        this.setVisible(true);
        this.setAlwaysOnTop(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label37 = new javax.swing.JPanel();
        jButton32 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LUNLabel = new javax.swing.JLabel();
        MARLabel = new javax.swing.JLabel();
        MERLabel = new javax.swing.JLabel();
        GIOLabel = new javax.swing.JLabel();
        VENLabel = new javax.swing.JLabel();
        SABLabel = new javax.swing.JLabel();
        DOMLabel = new javax.swing.JLabel();
        Label10 = new javax.swing.JLabel();
        Label20 = new javax.swing.JLabel();
        Label30 = new javax.swing.JLabel();
        Label11 = new javax.swing.JLabel();
        Label21 = new javax.swing.JLabel();
        Label31 = new javax.swing.JLabel();
        Label12 = new javax.swing.JLabel();
        Label22 = new javax.swing.JLabel();
        Label32 = new javax.swing.JLabel();
        Label13 = new javax.swing.JLabel();
        Label23 = new javax.swing.JLabel();
        Label33 = new javax.swing.JLabel();
        Label24 = new javax.swing.JLabel();
        Label34 = new javax.swing.JLabel();
        Label14 = new javax.swing.JLabel();
        Label15 = new javax.swing.JLabel();
        Label35 = new javax.swing.JLabel();
        Label25 = new javax.swing.JLabel();
        Label36 = new javax.swing.JLabel();
        Label26 = new javax.swing.JLabel();
        Label16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Label37.setBackground(new java.awt.Color(255, 248, 238));
        Label37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Label37.setFocusable(false);
        Label37.setPreferredSize(new java.awt.Dimension(1440, 810));

        jButton32.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        jButton32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/closeIcon.png"))); // NOI18N
        jButton32.setBorder(null);
        jButton32.setContentAreaFilled(false);
        jButton32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton32.setPreferredSize(new java.awt.Dimension(65, 65));
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Impiegato Selezionato: ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Matricola:");

        jLabel3.setText("jLabel2");

        LUNLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        LUNLabel.setForeground(new java.awt.Color(0, 0, 0));
        LUNLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LUNLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrarioCell.png"))); // NOI18N
        LUNLabel.setText("LUN");
        LUNLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        MARLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        MARLabel.setForeground(new java.awt.Color(0, 0, 0));
        MARLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MARLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrarioCell.png"))); // NOI18N
        MARLabel.setText("MAR");
        MARLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        MERLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        MERLabel.setForeground(new java.awt.Color(0, 0, 0));
        MERLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MERLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrarioCell.png"))); // NOI18N
        MERLabel.setText("MER");
        MERLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        GIOLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        GIOLabel.setForeground(new java.awt.Color(0, 0, 0));
        GIOLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        GIOLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrarioCell.png"))); // NOI18N
        GIOLabel.setText("GIO");
        GIOLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        VENLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        VENLabel.setForeground(new java.awt.Color(0, 0, 0));
        VENLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        VENLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrarioCell.png"))); // NOI18N
        VENLabel.setText("VEN");
        VENLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        SABLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        SABLabel.setForeground(new java.awt.Color(0, 0, 0));
        SABLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SABLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrarioCell.png"))); // NOI18N
        SABLabel.setText("SAB");
        SABLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        DOMLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        DOMLabel.setForeground(new java.awt.Color(0, 0, 0));
        DOMLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        DOMLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrarioCell.png"))); // NOI18N
        DOMLabel.setText("DOM");
        DOMLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Label10.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Label10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Label10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrarioCell.png"))); // NOI18N
        Label10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Label20.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Label20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Label20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrarioCell.png"))); // NOI18N
        Label20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Label30.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Label30.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Label30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrarioCell.png"))); // NOI18N
        Label30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Label11.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Label11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Label11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrarioCell.png"))); // NOI18N
        Label11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Label21.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Label21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Label21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrarioCell.png"))); // NOI18N
        Label21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Label31.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Label31.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Label31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrarioCell.png"))); // NOI18N
        Label31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Label12.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Label12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Label12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrarioCell.png"))); // NOI18N
        Label12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Label22.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Label22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Label22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrarioCell.png"))); // NOI18N
        Label22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Label32.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Label32.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Label32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrarioCell.png"))); // NOI18N
        Label32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Label13.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Label13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Label13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrarioCell.png"))); // NOI18N
        Label13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Label23.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Label23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Label23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrarioCell.png"))); // NOI18N
        Label23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Label33.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Label33.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Label33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrarioCell.png"))); // NOI18N
        Label33.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Label24.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Label24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Label24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrarioCell.png"))); // NOI18N
        Label24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Label34.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Label34.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Label34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrarioCell.png"))); // NOI18N
        Label34.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Label14.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Label14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Label14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrarioCell.png"))); // NOI18N
        Label14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Label15.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Label15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Label15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrarioCell.png"))); // NOI18N
        Label15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Label35.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Label35.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Label35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrarioCell.png"))); // NOI18N
        Label35.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Label25.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Label25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Label25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrarioCell.png"))); // NOI18N
        Label25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Label36.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Label36.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Label36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrarioCell.png"))); // NOI18N
        Label36.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Label26.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Label26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Label26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrarioCell.png"))); // NOI18N
        Label26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Label16.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Label16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Label16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OrarioCell.png"))); // NOI18N
        Label16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout Label37Layout = new javax.swing.GroupLayout(Label37);
        Label37.setLayout(Label37Layout);
        Label37Layout.setHorizontalGroup(
            Label37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Label37Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 897, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(Label37Layout.createSequentialGroup()
                .addGroup(Label37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Label37Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(Label37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LUNLabel)
                            .addComponent(Label10)
                            .addComponent(Label20)
                            .addComponent(Label30))
                        .addGap(20, 20, 20)
                        .addGroup(Label37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(MARLabel)
                            .addGroup(Label37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Label11)
                                .addComponent(Label21)
                                .addComponent(Label31)))
                        .addGroup(Label37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Label37Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(MERLabel)
                                .addGap(20, 20, 20)
                                .addComponent(GIOLabel))
                            .addGroup(Label37Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(Label37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label12)
                                    .addComponent(Label22)
                                    .addComponent(Label32))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(Label37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label13)
                                    .addComponent(Label23)
                                    .addComponent(Label33))))
                        .addGroup(Label37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Label37Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(VENLabel)
                                .addGap(20, 20, 20)
                                .addComponent(SABLabel))
                            .addGroup(Label37Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(Label37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label24)
                                    .addComponent(Label34)
                                    .addComponent(Label14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(Label37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label15)
                                    .addComponent(Label35)
                                    .addComponent(Label25))))
                        .addGap(20, 20, 20)
                        .addGroup(Label37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DOMLabel)
                            .addGroup(Label37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Label36)
                                .addComponent(Label26)
                                .addComponent(Label16))))
                    .addGroup(Label37Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        Label37Layout.setVerticalGroup(
            Label37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Label37Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(Label37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addComponent(jLabel2)
                .addGap(53, 53, 53)
                .addGroup(Label37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LUNLabel)
                    .addComponent(MARLabel)
                    .addComponent(MERLabel)
                    .addComponent(GIOLabel)
                    .addComponent(VENLabel)
                    .addComponent(SABLabel)
                    .addComponent(DOMLabel))
                .addGap(20, 20, 20)
                .addGroup(Label37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Label37Layout.createSequentialGroup()
                        .addComponent(Label10)
                        .addGap(20, 20, 20)
                        .addComponent(Label20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Label30))
                    .addGroup(Label37Layout.createSequentialGroup()
                        .addComponent(Label11)
                        .addGap(20, 20, 20)
                        .addComponent(Label21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Label31))
                    .addGroup(Label37Layout.createSequentialGroup()
                        .addComponent(Label12)
                        .addGap(20, 20, 20)
                        .addComponent(Label22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Label32))
                    .addGroup(Label37Layout.createSequentialGroup()
                        .addComponent(Label13)
                        .addGap(20, 20, 20)
                        .addComponent(Label23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Label33))
                    .addGroup(Label37Layout.createSequentialGroup()
                        .addComponent(Label14)
                        .addGap(20, 20, 20)
                        .addComponent(Label24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Label34))
                    .addGroup(Label37Layout.createSequentialGroup()
                        .addComponent(Label15)
                        .addGap(20, 20, 20)
                        .addComponent(Label25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Label35))
                    .addGroup(Label37Layout.createSequentialGroup()
                        .addComponent(Label16)
                        .addGap(20, 20, 20)
                        .addComponent(Label26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Label36)))
                .addContainerGap(240, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Label37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Label37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setBounds(240, 50, 1440, 650);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        // TODO add your handling code here:
        OSC.DisposeWindow(this);
    }//GEN-LAST:event_jButton32ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrarioImpiegato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrarioImpiegato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrarioImpiegato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrarioImpiegato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        new OrarioImpiegato(null).setVisible(true);
        /* Create and display the form */
 /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DOMLabel;
    private javax.swing.JLabel GIOLabel;
    private javax.swing.JLabel LUNLabel;
    private javax.swing.JLabel Label10;
    private javax.swing.JLabel Label11;
    private javax.swing.JLabel Label12;
    private javax.swing.JLabel Label13;
    private javax.swing.JLabel Label14;
    private javax.swing.JLabel Label15;
    private javax.swing.JLabel Label16;
    private javax.swing.JLabel Label20;
    private javax.swing.JLabel Label21;
    private javax.swing.JLabel Label22;
    private javax.swing.JLabel Label23;
    private javax.swing.JLabel Label24;
    private javax.swing.JLabel Label25;
    private javax.swing.JLabel Label26;
    private javax.swing.JLabel Label30;
    private javax.swing.JLabel Label31;
    private javax.swing.JLabel Label32;
    private javax.swing.JLabel Label33;
    private javax.swing.JLabel Label34;
    private javax.swing.JLabel Label35;
    private javax.swing.JLabel Label36;
    private javax.swing.JPanel Label37;
    private javax.swing.JLabel MARLabel;
    private javax.swing.JLabel MERLabel;
    private javax.swing.JLabel SABLabel;
    private javax.swing.JLabel VENLabel;
    private javax.swing.JButton jButton32;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    private OrariStipendiControl OSC = new OrariStipendiControl();

    public JLabel getLabel10() {
        return Label10;
    }

    public JLabel getLabel11() {
        return Label11;
    }

    public JLabel getLabel12() {
        return Label12;
    }

    public JLabel getLabel13() {
        return Label13;
    }

    public JLabel getLabel14() {
        return Label14;
    }

    public JLabel getLabel15() {
        return Label15;
    }

    public JLabel getLabel16() {
        return Label16;
    }

    public JLabel getLabel20() {
        return Label20;
    }

    public JLabel getLabel21() {
        return Label21;
    }

    public JLabel getLabel22() {
        return Label22;
    }

    public JLabel getLabel23() {
        return Label23;
    }

    public JLabel getLabel24() {
        return Label24;
    }

    public JLabel getLabel25() {
        return Label25;
    }

    public JLabel getLabel26() {
        return Label26;
    }

    public JLabel getLabel30() {
        return Label30;
    }

    public JLabel getLabel31() {
        return Label31;
    }

    public JLabel getLabel32() {
        return Label32;
    }

    public JLabel getLabel33() {
        return Label33;
    }

    public JLabel getLabel34() {
        return Label34;
    }

    public JLabel getLabel35() {
        return Label35;
    }

    public JLabel getLabel36() {
        return Label36;
    }

}
