package view;

import com.mysql.cj.protocol.Resultset;
import view.style.InfoReqBoxCard;
import controller.AreaPersonale.RichiesteControl;
import java.awt.Dimension;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JPanel;
import view.style.ScrollBarCustom;

/*
* PER VERIFICARE IL FUNZIONAMENTO DELLA PAGINA PREMERE IL TASTO HOME
* VERRANNO AGGIUNTE DELLE CARD RICHIESTA ALLA LISTA
 */
/**
 *
 * @author Davide
 */
public class RichiestaList extends javax.swing.JFrame {

    int cardCount;
    RichiesteControl RC;
    ResultSet rs;
    private ArrayList<InfoReqBoxCard> richieste = new ArrayList<InfoReqBoxCard>();

    public JButton getHomeButton() {
        return homeButton;
    }

   

    public ArrayList<InfoReqBoxCard> getRichieste() {
        return richieste;
    }

    public RichiestaList(RichiesteControl RiC, ResultSet rst) {

        this.RC = RiC;
        this.rs = rst;
        initComponents();
        cardCount = 0;
        listScrollPane.setVerticalScrollBar(new ScrollBarCustom());
        try {
            while (rs.next()) {
                addInfoPane(RC, rs.getString("nome"), rs.getString("cognome"), rs.getString("tipo"), rs.getString("data_scadenza"), rs.getString("dati_richiesta"),rs.getString("id"),rs.getString("testo"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(RichiestaList.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(true);
        this.setAlwaysOnTop(true);
    }

    /**
     * *****TEST - DA ELIMINARE******
     */
    /* public void addInfoPane() {
        listPanel.add(new InfoReqBoxCard("NomeProvaLungo CognomeProvaLungo", "NomeTipoLungo", "12/12/22"));
        cardCount++;
        //System.out.println("Prima: " + jPanel5.getSize().height);
        listPanel.setPreferredSize(new Dimension(listPanel.getPreferredSize().width, cardCount * 123));
        //System.out.println("Dopo: " + jPanel5.getSize().height);
        listPanel.revalidate();
    }*/
    /**
     * ******************************
     */
    public void addInfoPane(RichiesteControl RC, String nomeMittente, String cognomeMittente, String tipoRichiesta, String dataScadenza, String dati, String id, String motivazione) {
        this.RC = RC;
        InfoReqBoxCard infoBox = new InfoReqBoxCard(RC, nomeMittente, cognomeMittente, tipoRichiesta, dataScadenza, dati, id, motivazione);
        listPanel.add(infoBox);
        richieste.add(infoBox);
        cardCount++;
        //System.out.println("Prima: " + jPanel5.getSize().height);
        listPanel.setPreferredSize(new Dimension(listPanel.getPreferredSize().width, cardCount * 123));
        //System.out.println("Dopo: " + jPanel5.getSize().height);
        listPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        listScrollPane = new javax.swing.JScrollPane();
        listPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        mainPanel.setBackground(new java.awt.Color(255, 248, 238));

        jPanel1.setBackground(new java.awt.Color(255, 248, 238));
        jPanel1.setLayout(null);

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HomeButton.png"))); // NOI18N
        homeButton.setBorder(null);
        homeButton.setBorderPainted(false);
        homeButton.setContentAreaFilled(false);
        homeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeButton.setFocusPainted(false);
        homeButton.setFocusable(false);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(homeButton);
        homeButton.setBounds(40, 40, 100, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Angolo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 200, 195);

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBar(null);

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(255, 248, 238));
        jTextPane1.setBorder(null);
        jTextPane1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(0, 0, 0));
        jTextPane1.setText("Lista Richieste");
        jTextPane1.setFocusable(false);
        jScrollPane1.setViewportView(jTextPane1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(210, 60, 420, 70);

        jPanel4.setBackground(new java.awt.Color(255, 248, 238));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(255, 248, 238));
        jPanel2.setPreferredSize(new java.awt.Dimension(1235, 826));

        listScrollPane.setBorder(null);
        listScrollPane.setHorizontalScrollBar(null);
        listScrollPane.setPreferredSize(new java.awt.Dimension(1225, 100));

        listPanel.setBackground(new java.awt.Color(255, 248, 238));
        listPanel.setPreferredSize(new java.awt.Dimension(1201, 0));
        listPanel.setRequestFocusEnabled(false);
        listPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 10));
        listScrollPane.setViewportView(listPanel);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1235, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel2, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1614, Short.MAX_VALUE)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE))
        );

        getContentPane().add(mainPanel);

        setBounds(0, 0, 1920, 1080);
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
            RC.DisposeWindow(this);
    }//GEN-LAST:event_homeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new RichiestaList(null, null).setVisible(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JPanel listPanel;
    private javax.swing.JScrollPane listScrollPane;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables

    public JPanel getListPanel() {
        return listPanel;
    }

}
