package view;

import controller.AreaPersonale.OrariStipendiControl;
import controller.AreaPersonale.RichiesteControl;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Monica Salluzzo
 */
public class RitardoForm extends javax.swing.JFrame {

    /**
     * Creates new form RichiestaFrom
     */
    ResultSet rs;
    OrariStipendiControl OSC;

    String nome;
    String cognome;
    int n = -1;
    int d = 0;
    ArrayList<Date> date = new ArrayList<Date>();
    ArrayList<String> motivi = new ArrayList<String>();
    Date dataselezionata = null;
    String motivoselezionato = null;

    public RitardoForm(ResultSet rs, OrariStipendiControl OSC) {
        this.rs = rs;
        this.OSC = OSC;
        initComponents();
        try {
            while (rs.next()) {
                nome = rs.getString("nome");
                cognome = rs.getString("cognome");
                date.add(rs.getDate("data_"));
                motivi.add(rs.getString("motivo"));
                d++;
                n = 0;
            }
        } catch (SQLException ex) {
            Logger.getLogger(RitardoForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(true);
        this.setAlwaysOnTop(true);

        if (d != 0) {
            dataselezionata = date.get(n);
            motivoselezionato = motivi.get(n);
            denLabel.setText(String.valueOf(d));
            numLabel.setText(String.valueOf(n+1));
            jLabel1.setText("Impiegato: " + nome + " " + cognome);
            jLabel3.setText("Data: " + dataselezionata);
            jTextPane1.setText(motivoselezionato);
        } else {
            denLabel.setText("n/a");
            numLabel.setText("n/a");
            jLabel1.setText("Impiegato: " + nome + " " + cognome);
            jLabel3.setText("Data: n/a");
            jTextPane1.setText("nessun ritardo effettuato");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        prevMonthButton = new javax.swing.JButton();
        denLabel = new javax.swing.JLabel();
        MonthLabel1 = new javax.swing.JLabel();
        numLabel = new javax.swing.JLabel();
        nextMonthButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 248, 238));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(1440, 810));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 34)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Mittente : Nome Cognome");
        jLabel1.setPreferredSize(new java.awt.Dimension(413, 48));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 50, 413, 48);

        jButton1.setBackground(new java.awt.Color(255, 248, 238));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CloseIcon.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1330, 51, 59, 59);

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(219, 213, 205));
        jTextPane1.setBorder(null);
        jTextPane1.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        jTextPane1.setText("Messaggio...");
        jTextPane1.setToolTipText("");
        jScrollPane1.setViewportView(jTextPane1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(150, 233, 1140, 344);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 34)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Data : Data");
        jLabel3.setPreferredSize(new java.awt.Dimension(413, 48));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 90, 413, 49);

        prevMonthButton.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        prevMonthButton.setForeground(new java.awt.Color(0, 0, 0));
        prevMonthButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/40x40ButtonBeige.png"))); // NOI18N
        prevMonthButton.setText("←");
        prevMonthButton.setAlignmentY(0.0F);
        prevMonthButton.setBorder(null);
        prevMonthButton.setBorderPainted(false);
        prevMonthButton.setContentAreaFilled(false);
        prevMonthButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        prevMonthButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        prevMonthButton.setIconTextGap(0);
        prevMonthButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        prevMonthButton.setPreferredSize(new java.awt.Dimension(45, 45));
        prevMonthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevMonthButtonActionPerformed(evt);
            }
        });
        jPanel1.add(prevMonthButton);
        prevMonthButton.setBounds(50, 150, 45, 45);

        denLabel.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        denLabel.setForeground(new java.awt.Color(0, 0, 0));
        denLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        denLabel.setText("14");
        denLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(denLabel);
        denLabel.setBounds(160, 150, 86, 43);

        MonthLabel1.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        MonthLabel1.setForeground(new java.awt.Color(0, 0, 0));
        MonthLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MonthLabel1.setText("/");
        MonthLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(MonthLabel1);
        MonthLabel1.setBounds(125, 150, 86, 43);

        numLabel.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        numLabel.setForeground(new java.awt.Color(0, 0, 0));
        numLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numLabel.setText("01");
        numLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(numLabel);
        numLabel.setBounds(90, 150, 86, 43);

        nextMonthButton.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        nextMonthButton.setForeground(new java.awt.Color(0, 0, 0));
        nextMonthButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/40x40ButtonBeige.png"))); // NOI18N
        nextMonthButton.setText("→");
        nextMonthButton.setAlignmentY(0.0F);
        nextMonthButton.setBorder(null);
        nextMonthButton.setBorderPainted(false);
        nextMonthButton.setContentAreaFilled(false);
        nextMonthButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nextMonthButton.setDisplayedMnemonicIndex(0);
        nextMonthButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nextMonthButton.setIconTextGap(0);
        nextMonthButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        nextMonthButton.setPreferredSize(new java.awt.Dimension(45, 45));
        nextMonthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextMonthButtonActionPerformed(evt);
            }
        });
        jPanel1.add(nextMonthButton);
        nextMonthButton.setBounds(239, 150, 45, 45);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setBounds(240, 50, 1440, 810);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        OSC.DisposeWindow(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void prevMonthButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevMonthButtonActionPerformed
        // TODO add your handling code here:
        n = (((n - 1) % (d+1)) + (d+1)) % (d+1);
        dataselezionata = date.get(n);
        motivoselezionato = motivi.get(n);
        jLabel3.setText("Data: " + dataselezionata);
        jTextPane1.setText(motivoselezionato);
        numLabel.setText(String.valueOf(n+1));
    }//GEN-LAST:event_prevMonthButtonActionPerformed

    private void nextMonthButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextMonthButtonActionPerformed
        n = (n + 1) % d;
        dataselezionata = date.get(n);
        motivoselezionato = motivi.get(n);
        jLabel3.setText("Data: " + dataselezionata);
        jTextPane1.setText(motivoselezionato);
        numLabel.setText(String.valueOf(n+1));

    }//GEN-LAST:event_nextMonthButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RitardoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RitardoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RitardoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RitardoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
 /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RichiestaForm(null);
            }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
 /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RichiestaForm(null);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MonthLabel1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel denLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton nextMonthButton;
    private javax.swing.JLabel numLabel;
    private javax.swing.JButton prevMonthButton;
    // End of variables declaration//GEN-END:variables
}
