package view;

import controller.OrariStipendiControl;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Monica Salluzzo
 */
public class StipendioImpiegato extends javax.swing.JFrame {

    /**
     * Creates new form StipendioImpiegatoDatore
     */
    int meseIndex;
    int annoIndex;
    public String[] mesi = new String[]{"Gennaio", "Febbraio", "Marzo", "Aprile", "Maggio", "Giugno", "Luglio", "Agosto", "Settembre", "Ottobre", "Novembre", "Dicembre"};

    public StipendioImpiegato(OrariStipendiControl OSC) {
        this.OSC = OSC;
        initComponents();
        meseIndex = 0;
        MonthLabel.setText(mesi[meseIndex]);
        annoIndex = 2023;

        ImpiegatoLabel.setVisible(false);
        MatricolaLabel.setVisible(false);
    }

    public StipendioImpiegato(OrariStipendiControl OSC, String nome, String cognome, String matricola) {
        this.OSC = OSC;
        initComponents();
        ImpiegatoLabel.setText("Impiegato Selezionato: " + nome + " " + cognome);
        MatricolaLabel.setText("Matricola: " + matricola);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CloseButton = new javax.swing.JButton();
        ImpiegatoLabel = new javax.swing.JLabel();
        MalattiaLabel = new javax.swing.JLabel();
        MatricolaLabel = new javax.swing.JLabel();
        CongedoParentaleLabel = new javax.swing.JLabel();
        TotaleLabel = new javax.swing.JLabel();
        BaseLabel = new javax.swing.JLabel();
        BonusLabel = new javax.swing.JLabel();
        StraordinariLabel = new javax.swing.JLabel();
        StipendioTotale = new javax.swing.JLabel();
        StipendioBase = new javax.swing.JLabel();
        StipendioBonus = new javax.swing.JLabel();
        StipendioStraordinari = new javax.swing.JLabel();
        StipendioMalattia = new javax.swing.JLabel();
        StipendioCongedoParentale = new javax.swing.JLabel();
        Separatore = new javax.swing.JSeparator();
        prevMonthButton = new javax.swing.JButton();
        nextMonthButton = new javax.swing.JButton();
        MonthLabel = new javax.swing.JLabel();
        prevYearButton = new javax.swing.JButton();
        nextYearButton = new javax.swing.JButton();
        YearLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 248, 238));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(1440, 810));
        jPanel1.setLayout(null);

        CloseButton.setBackground(new java.awt.Color(255, 248, 238));
        CloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/closeIcon.png"))); // NOI18N
        CloseButton.setBorder(null);
        CloseButton.setPreferredSize(new java.awt.Dimension(59, 59));
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CloseButton);
        CloseButton.setBounds(1344, 51, 45, 45);

        ImpiegatoLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        ImpiegatoLabel.setForeground(new java.awt.Color(0, 0, 0));
        ImpiegatoLabel.setText("Impiegato Selezionato: ");
        jPanel1.add(ImpiegatoLabel);
        ImpiegatoLabel.setBounds(125, 50, 373, 48);

        MalattiaLabel.setBackground(new java.awt.Color(255, 248, 238));
        MalattiaLabel.setFont(new java.awt.Font("Segoe UI", 0, 34)); // NOI18N
        MalattiaLabel.setForeground(new java.awt.Color(0, 0, 0));
        MalattiaLabel.setText("Stipendio Malattia");
        jPanel1.add(MalattiaLabel);
        MalattiaLabel.setBounds(160, 435, 274, 46);

        MatricolaLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        MatricolaLabel.setForeground(new java.awt.Color(0, 0, 0));
        MatricolaLabel.setText("Matricola:");
        jPanel1.add(MatricolaLabel);
        MatricolaLabel.setBounds(125, 100, 157, 48);

        CongedoParentaleLabel.setBackground(new java.awt.Color(255, 248, 238));
        CongedoParentaleLabel.setFont(new java.awt.Font("Segoe UI", 0, 34)); // NOI18N
        CongedoParentaleLabel.setForeground(new java.awt.Color(0, 0, 0));
        CongedoParentaleLabel.setText("Stipendio Congedo Parentale");
        jPanel1.add(CongedoParentaleLabel);
        CongedoParentaleLabel.setBounds(160, 500, 439, 46);

        TotaleLabel.setBackground(new java.awt.Color(255, 248, 238));
        TotaleLabel.setFont(new java.awt.Font("Segoe UI", 0, 34)); // NOI18N
        TotaleLabel.setForeground(new java.awt.Color(0, 0, 0));
        TotaleLabel.setText("Totale");
        jPanel1.add(TotaleLabel);
        TotaleLabel.setBounds(160, 590, 93, 46);

        BaseLabel.setBackground(new java.awt.Color(255, 248, 238));
        BaseLabel.setFont(new java.awt.Font("Segoe UI", 0, 34)); // NOI18N
        BaseLabel.setForeground(new java.awt.Color(0, 0, 0));
        BaseLabel.setText("Stipendio Base");
        jPanel1.add(BaseLabel);
        BaseLabel.setBounds(160, 240, 220, 46);

        BonusLabel.setBackground(new java.awt.Color(255, 248, 238));
        BonusLabel.setFont(new java.awt.Font("Segoe UI", 0, 34)); // NOI18N
        BonusLabel.setForeground(new java.awt.Color(0, 0, 0));
        BonusLabel.setText("Stipendio Bonus");
        jPanel1.add(BonusLabel);
        BonusLabel.setBounds(160, 310, 243, 46);

        StraordinariLabel.setBackground(new java.awt.Color(255, 248, 238));
        StraordinariLabel.setFont(new java.awt.Font("Segoe UI", 0, 34)); // NOI18N
        StraordinariLabel.setForeground(new java.awt.Color(0, 0, 0));
        StraordinariLabel.setText("Stipendio Straordinari");
        jPanel1.add(StraordinariLabel);
        StraordinariLabel.setBounds(160, 370, 327, 46);

        StipendioTotale.setBackground(new java.awt.Color(255, 248, 238));
        StipendioTotale.setFont(new java.awt.Font("Segoe UI", 0, 34)); // NOI18N
        StipendioTotale.setForeground(new java.awt.Color(0, 0, 0));
        StipendioTotale.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        StipendioTotale.setText("+200.00€");
        StipendioTotale.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(StipendioTotale);
        StipendioTotale.setBounds(935, 590, 340, 46);

        StipendioBase.setBackground(new java.awt.Color(255, 248, 238));
        StipendioBase.setFont(new java.awt.Font("Segoe UI", 0, 34)); // NOI18N
        StipendioBase.setForeground(new java.awt.Color(0, 0, 0));
        StipendioBase.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        StipendioBase.setText("+200.00€");
        StipendioBase.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(StipendioBase);
        StipendioBase.setBounds(935, 240, 340, 46);

        StipendioBonus.setBackground(new java.awt.Color(255, 248, 238));
        StipendioBonus.setFont(new java.awt.Font("Segoe UI", 0, 34)); // NOI18N
        StipendioBonus.setForeground(new java.awt.Color(0, 0, 0));
        StipendioBonus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        StipendioBonus.setText("+200.00€");
        StipendioBonus.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(StipendioBonus);
        StipendioBonus.setBounds(935, 310, 340, 46);

        StipendioStraordinari.setBackground(new java.awt.Color(255, 248, 238));
        StipendioStraordinari.setFont(new java.awt.Font("Segoe UI", 0, 34)); // NOI18N
        StipendioStraordinari.setForeground(new java.awt.Color(0, 0, 0));
        StipendioStraordinari.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        StipendioStraordinari.setText("+200.00€");
        StipendioStraordinari.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(StipendioStraordinari);
        StipendioStraordinari.setBounds(935, 380, 340, 46);

        StipendioMalattia.setBackground(new java.awt.Color(255, 248, 238));
        StipendioMalattia.setFont(new java.awt.Font("Segoe UI", 0, 34)); // NOI18N
        StipendioMalattia.setForeground(new java.awt.Color(0, 0, 0));
        StipendioMalattia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        StipendioMalattia.setText("+200.00€");
        StipendioMalattia.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(StipendioMalattia);
        StipendioMalattia.setBounds(935, 444, 340, 46);

        StipendioCongedoParentale.setBackground(new java.awt.Color(255, 248, 238));
        StipendioCongedoParentale.setFont(new java.awt.Font("Segoe UI", 0, 34)); // NOI18N
        StipendioCongedoParentale.setForeground(new java.awt.Color(0, 0, 0));
        StipendioCongedoParentale.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        StipendioCongedoParentale.setText("+200.00€");
        StipendioCongedoParentale.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(StipendioCongedoParentale);
        StipendioCongedoParentale.setBounds(935, 511, 340, 46);

        Separatore.setBackground(new java.awt.Color(38, 38, 38));
        Separatore.setForeground(new java.awt.Color(38, 38, 38));
        jPanel1.add(Separatore);
        Separatore.setBounds(160, 570, 1120, 3);

        prevMonthButton.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        prevMonthButton.setForeground(new java.awt.Color(0, 0, 0));
        prevMonthButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/40x40ButtonBeige.png"))); // NOI18N
        prevMonthButton.setText("←");
        prevMonthButton.setAlignmentY(0.0F);
        prevMonthButton.setBorder(null);
        prevMonthButton.setBorderPainted(false);
        prevMonthButton.setContentAreaFilled(false);
        prevMonthButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        prevMonthButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        prevMonthButton.setIconTextGap(0);
        prevMonthButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        prevMonthButton.setPreferredSize(new java.awt.Dimension(45, 45));
        prevMonthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevMonthButtonActionPerformed(evt);
            }
        });
        jPanel1.add(prevMonthButton);
        prevMonthButton.setBounds(160, 680, 45, 45);

        nextMonthButton.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        nextMonthButton.setForeground(new java.awt.Color(0, 0, 0));
        nextMonthButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/40x40ButtonBeige.png"))); // NOI18N
        nextMonthButton.setText("→");
        nextMonthButton.setAlignmentY(0.0F);
        nextMonthButton.setBorder(null);
        nextMonthButton.setBorderPainted(false);
        nextMonthButton.setContentAreaFilled(false);
        nextMonthButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nextMonthButton.setDisplayedMnemonicIndex(0);
        nextMonthButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nextMonthButton.setIconTextGap(0);
        nextMonthButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        nextMonthButton.setPreferredSize(new java.awt.Dimension(45, 45));
        nextMonthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextMonthButtonActionPerformed(evt);
            }
        });
        jPanel1.add(nextMonthButton);
        nextMonthButton.setBounds(349, 680, 45, 45);

        MonthLabel.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        MonthLabel.setForeground(new java.awt.Color(0, 0, 0));
        MonthLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MonthLabel.setText("cottu");
        jPanel1.add(MonthLabel);
        MonthLabel.setBounds(161, 680, 228, 43);

        prevYearButton.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        prevYearButton.setForeground(new java.awt.Color(0, 0, 0));
        prevYearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/40x40ButtonBeige.png"))); // NOI18N
        prevYearButton.setText("←");
        prevYearButton.setAlignmentY(0.0F);
        prevYearButton.setBorder(null);
        prevYearButton.setBorderPainted(false);
        prevYearButton.setContentAreaFilled(false);
        prevYearButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        prevYearButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        prevYearButton.setIconTextGap(0);
        prevYearButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        prevYearButton.setPreferredSize(new java.awt.Dimension(45, 45));
        prevYearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevYearButtonActionPerformed(evt);
            }
        });
        jPanel1.add(prevYearButton);
        prevYearButton.setBounds(470, 680, 45, 45);

        nextYearButton.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        nextYearButton.setForeground(new java.awt.Color(0, 0, 0));
        nextYearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/40x40ButtonBeige.png"))); // NOI18N
        nextYearButton.setText("→");
        nextYearButton.setAlignmentY(0.0F);
        nextYearButton.setBorder(null);
        nextYearButton.setBorderPainted(false);
        nextYearButton.setContentAreaFilled(false);
        nextYearButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nextYearButton.setDisplayedMnemonicIndex(0);
        nextYearButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nextYearButton.setIconTextGap(0);
        nextYearButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        nextYearButton.setPreferredSize(new java.awt.Dimension(45, 45));
        nextYearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextYearButtonActionPerformed(evt);
            }
        });
        jPanel1.add(nextYearButton);
        nextYearButton.setBounds(650, 680, 45, 45);

        YearLabel.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        YearLabel.setForeground(new java.awt.Color(0, 0, 0));
        YearLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        YearLabel.setText("cottu");
        jPanel1.add(YearLabel);
        YearLabel.setBounds(470, 680, 228, 43);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1440, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setBounds(240, 50, 1440, 810);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        // TODO add your handling code here:
        OSC.DisposeWindow(this);

    }//GEN-LAST:event_CloseButtonActionPerformed

    private void prevMonthButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevMonthButtonActionPerformed
        // TODO add your handling code here:
        meseIndex = (((meseIndex - 1) % 12) + 12) % 12;
        MonthLabel.setText(mesi[meseIndex]);
    }//GEN-LAST:event_prevMonthButtonActionPerformed

    private void nextMonthButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextMonthButtonActionPerformed
        meseIndex = (meseIndex + 1) % 12;
        MonthLabel.setText(mesi[meseIndex]);
    }//GEN-LAST:event_nextMonthButtonActionPerformed

    private void prevYearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevYearButtonActionPerformed
        annoIndex = annoIndex - 1;
        YearLabel.setText(String.valueOf(annoIndex));
    }//GEN-LAST:event_prevYearButtonActionPerformed

    private void nextYearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextYearButtonActionPerformed
        // TODO add your handling code here:
        annoIndex = annoIndex + 1;
        YearLabel.setText(String.valueOf(annoIndex));


    }//GEN-LAST:event_nextYearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StipendioImpiegatoDatore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StipendioImpiegatoDatore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StipendioImpiegatoDatore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StipendioImpiegatoDatore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StipendioImpiegatoDatore().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BaseLabel;
    private javax.swing.JLabel BonusLabel;
    private javax.swing.JButton CloseButton;
    private javax.swing.JLabel CongedoParentaleLabel;
    private javax.swing.JLabel ImpiegatoLabel;
    private javax.swing.JLabel MalattiaLabel;
    private javax.swing.JLabel MatricolaLabel;
    private javax.swing.JLabel MonthLabel;
    private javax.swing.JSeparator Separatore;
    private javax.swing.JLabel StipendioBase;
    private javax.swing.JLabel StipendioBonus;
    private javax.swing.JLabel StipendioCongedoParentale;
    private javax.swing.JLabel StipendioMalattia;
    private javax.swing.JLabel StipendioStraordinari;
    private javax.swing.JLabel StipendioTotale;
    private javax.swing.JLabel StraordinariLabel;
    private javax.swing.JLabel TotaleLabel;
    private javax.swing.JLabel YearLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nextMonthButton;
    private javax.swing.JButton nextYearButton;
    private javax.swing.JButton prevMonthButton;
    private javax.swing.JButton prevYearButton;
    // End of variables declaration//GEN-END:variables

    private OrariStipendiControl OSC = new OrariStipendiControl();

}
